modules:
  - type: files
    files:
      - etc: /etc
          # copies stuff to /etc that will be needed by the installer
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.
  # Enable the Chrome repo already on the UBlue Silverblue image and fix the RPM GPG Pubkey issue.
  # Should theoretically enable installation of Chrome w/ RPM-OSTree, but does not work
  # - type: script
  #   scripts:
  #     - enable-chrome-yum-repo.sh
  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      # - https://rrenomeron.github.io/ublue-tr/repos/vscode.repo
    install:
      # - micro
      # - starship      
      - langpacks-en
      - nss-tools
      - google-roboto-mono-fonts
      - google-roboto-fonts
      - google-crosextra-caladea-fonts
      - google-crosextra-carlito-fonts
      - liberation-fonts
      - sil-charis-fonts
      - sil-charis-compact-fonts
      - sil-andika-fonts
      - sil-andika-compact-fonts
      - fontawesome-fonts
      - libreoffice-opensymbol-fonts
      - variety
      # - google-chrome-stable              

    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
        #- com.google.Chrome
        - com.discordapp.Discord        
        - org.gimp.GIMP 
        - org.libreoffice.LibreOffice        
        - com.nextcloud.desktopclient.nextcloud
        - com.spotify.Client 
        - org.audacityteam.Audacity org.sqlitebrowser.sqlitebrowser 
        - org.openshot.OpenShot 
        - io.dbeaver.DBeaverCommunity
        - org.darktable.Darktable
        - org.gnome.Totem
        - org.gnome.Snapshot
        - us.zoom.Zoom
        - ca.desrt.dconf-editor
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - org.gnome.Weather
        - org.gnome.Evince 
        - org.gnome.Loupe
        - org.gnome.baobab
        - org.fedoraproject.MediaWriter
        - io.github.flattool.Warehouse
        # - google-chrome-stable

      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
        # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: gschema-overrides  # this sets up our dconf overrides
    include:
      - 50_tr-fedora.gschema.override
  - type: script
    # We run this to put get our home CA in the system circle of trust
    snippets:
      - "update-ca-trust extract"
    scripts:      
      - chrome-workaround-manual-install.sh
      - install-system76-wallpaper.sh

  - type: bling
    install:
      - dconf-update-service
