# image will be published to ghcr.io/<user>/<name>
name: bluefin-tr-40
# description will be included in the image's metadata
description: A Project Bluefin-based image with my personal preference baked in

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module

# Until we get the full refactor (which includes undoing some Bluefin choices I don't like),
# we'll just add our Chrome fixes and Variety
modules:
  - type: script
    scripts:
      - chrome-workaround-manual-install.sh
  - type: containerfile
    snippets:
      - "COPY config/files/usr/bin/check-chrome-version /usr/bin"
  - type: rpm-ostree
    repos:
    install:
      - variety
    
