modules:
- type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://rrenomeron.github.io/ublue-tr/repos/vscode.repo
    install:
      # - micro
      # - starship
      - libvirt
      - virt-manager
      - gnome-tweaks      
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-dash-to-dock 
      - code
      - liberation-fonts
      - cascadia-code-fonts
  - type: default-flatpaks
      system:
        install:
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - org.gnome.Weather
          - org.gnome.Evince 
          - org.gnome.Loupe
          - org.gnome.baobab
        remove:
          # - org.gnome.eog
