modules:
- type: files
  files:
    - dconf-ublue: /usr/etc/dconf/db/local.d
- type: script
  scripts:
    - ublue-get-files-from-bluefin.sh
- type: rpm-ostree
  repos:
  # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
  install:
    # - micro
    # - starship
    - libvirt
    - virt-manager
    - gnome-tweaks      
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-dash-to-dock 
    - gnome-shell-extension-blur-my-shell
    - gnome-shell-extension-logo-menu
    - code
    - liberation-fonts
    - cascadia-code-fonts
    - yaru-theme

