# yaml-language-server: $schema=https://schema.blue-build.org/module-stage-list-v1.json
modules:
  - type: dnf
    install:
      packages:
        - langpacks-en
        - nss-tools
        - socat
        - gnome-shell-extension-system-monitor-applet
        - netcat
        - fastfetch
    
